# -*- coding: utf-8 -*-
"""
Created on Tue Jan 17 10:12:16 2023

@author: marrog

Generate Visualiced output

Input: SAR image and image date.

Workflow outline:
    i) Extract corresponding MODIS image from NASA repository.
    ii) Resize and range normalise both input images.
    iii) Apply trained ViSual_IceD network to image pairs.

Output: ViSual_IceD segmented output.
"""

from osgeo import gdal
import image_properties
import extract_modis
import make_prediction_visualiced as mp
import preprocess_MODIS

VISUALICED_MODEL_FP = ".json"
VISUALICED_WEIGHTS_FP = ".hdf5"

# Input SAR image filename- this must be supplied.
SAR_FN = ".tiff"
# Input MODIS image filename- this will be extracted and generated by code.
MODIS_FP = ""
MODIS_FN = ".tiff"
# Format = yyyymmdd
IMAGE_DATE = ""
# Shell script to extract corresponding MODIS image.
SHELL_SCRIPT = ".sh"

# Resize and normalise SAR image and extract coords in list (coords)
processed_sar_array, coords = image_properties.extract_coords(SAR_FN,
                                                              IMAGE_DATE,
                                                              MODIS_FP)
# Extract concurrent MODIS image.
extract_modis.create_modis_image(SHELL_SCRIPT)

# Create array object of MODIS image.
MODIS_IMAGE = gdal.Open(MODIS_FN).ReadAsArray()

# Preprocess MODIS: resize to 240 m resolution and normalise to [-1,1]
MODIS_IMAGE_PREPROCESSED = preprocess_MODIS.resize_normalise_vis(MODIS_FN,
                                                                 MODIS_IMAGE)

# Segment image using ViSual_IceD network.
visualiced_output = mp.make_pred(MODIS_FN, MODIS_IMAGE_PREPROCESSED, SAR_FN,
                                 VISUALICED_MODEL_FP, VISUALICED_WEIGHTS_FP,
                                 IMAGE_DATE, processed_sar_array)
